### ISSUE TITLE
Unable to configure discovered devices

### ISSUE THREAD

**Issue by chedim** [SWW13/homeassistant-victron-ir-ble#1]
Great work on the plugin, thank you for creating it!

Right now I'm receiving ir-ble data from my solar charger and shunt using Signalk victron-ble plugin and then I push that data to HA through MQTT. Would really love to streamline the setup and was very excited about finding this plugin!

But:

After installing through HACS and restarting HA, both of my devices were discovered, but when I try to configure it, a configuration window with no inputs and only "Submit" button appears. Clicking "Submit" adds the devices in "failed to configure" state.

HA is running as a Docker container.

**Comment by chedim** [comment]
Got the following error messages in HA logs:

```
2023-11-19 14:43:17.955 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Sudo 12v Charger for victron_ir
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/victron_ir/__init__.py", line 24, in async_setup_entry
    data = VictronInstantReadoutData(entry.options[ENC_KEY])
                                     ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'enckey'
2023-11-19 14:43:25.030 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Sudo 48v Shunt for victron_ir
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/victron_ir/__init__.py", line 24, in async_setup_entry
    data = VictronInstantReadoutData(entry.options[ENC_KEY])
                                     ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'enckey'

```

**Comment by chedim** [comment]
Update: I was able to configure the devices by adding Victron integrations manually from Devices configuration page.

**Comment by SWW13** [comment]
Yeah this is a "known" issue, because i couldn't figure out how to make the discovery workflow work as expected.
Thanks for reporting anyway, maybe we can figure out how to fix it.
