### ISSUE TITLE
No readouts for 500A SmartShunt

### ISSUE THREAD

**Issue by chedim** [SWW13/homeassistant-victron-ir-ble#2]
<img width="1433" alt="Screenshot 2023-11-19 at 3 06 06 PM" src="https://github.com/SWW13/homeassistant-victron-ir-ble/assets/807041/922575d7-37a5-4445-a51a-478e37f5f1c5">

The integration tries to get solar power from a battery shunt.
Logs:
```
2023-11-19 15:06:55.149 ERROR (MainThread) [custom_components.victron_ir] Unexpected error updating Sudo 48v Shunt data: 'BatteryMonitorData' object has no attribute 'get_solar_power'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/passive_update_processor.py", line 373, in _async_handle_bluetooth_event
    update = self._update_method(service_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bluetooth_sensor_state_data/__init__.py", line 75, in update
    self._start_update(data)
  File "/config/custom_components/victron_ir/victron.py", line 63, in _start_update
    if sensor_data.get_solar_power() > 1500:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BatteryMonitorData' object has no attribute 'get_solar_power'
```

**Comment by chedim** [comment]
Working on a fix for this.
